### ISSUE TITLE
Not executing section 7b

### ISSUE THREAD

**Issue by brunocantellimogi** [sqldb360/sqldb360#87]
while trying to execute versions 20.2 and 20.1, 7b section could not be collected. Then, I tried version 19.2 and it worked.

**Comment by brunocantellimogi** [comment]
Database version is 12.1.0.2 and multitenant. I tried to execute only section 7b, but, it doesn't return any error(nohup log) or result in the report. Using version 19.2 SQLs are been collected.

**Comment by mauropagano** [comment]
Thanks, that's unfortunately a known issue.
I deleted the 20.x releases just to be sure nobody hits that again

The fix is part of a larger set of fix we have in the works but might take a bit (if you want to help / contribute just let me know!)

**Comment by davidkurtz** [comment]
I think this occurs because EDB360 was run connected to a PDB, while the AWR snapshots are run in the CDB.  If EDB360 is connected to the CDB it works correctly.  The reason is that the list of AWR reports to be generated is determined by a query (edb360_7a_cluster_query.sql) on DBA_HIST_SYS_TIME_MODEL.  If you are connected to the PDB you don't get any data from that or from CDB_HIST_SYS_TIME_MODEL.  I think this is more of a feature than a bug.

**Comment by abelmacias** [comment]
The reason is because the 7b query has errors in the way the skip variables and some aliases are placed in the query to manage the multitenant.
I am almost done with a fix and will submit soon but it was agreed that it was better to remove the release because this is not the only place with this problem.

**Comment by mauropagano** [comment]
Solved by #88
